---
- hosts: all
  become: true
  vars:
    create_containers: 1
    default_container_name: docker
    default_container_image: drorvt/whatismyip:1fffea471c333105e40ff09d480ea5c0533cac34
    default_container_command: curl 0.0.0.0:8000

  tasks:
    - name: Install aptitude using apt
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

    # - name: Add Docker GPG apt Key
    #   apt_key:
    #     url: https://download.docker.com/linux/ubuntu/gpg
    #     state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    
    - name: Checking docker on latest version
      apt: name=docker.io state=latest

    - name: Checking python
      apt: name=python state=latest

    - name: Checking docker-compose on latest version
      apt: name=docker-compose state=latest

    # Pull image specified by variable default_image from the Docker Hub
    - name:   
      docker_image:
        name: "{{ default_container_image }}"
        source: pull

    # Creates the number of containers defined by the variable create_containers, using default values
    - name: Create default containers
      docker_container:
        name: "{{ default_container_name }}{{ item }}"
        image: "{{ default_container_image }}"
        command: "{{ default_container_command }}"
        state: present
      with_sequence: count={{ create_containers }}
